theme: jekyll-theme-cayman
title: "Hierarchical Scene Coordinate Classification and Regression for Visual Localization"
description: "Xiaotian Li, Shuzhe Wang, Yi Zhao, Jakob Verbeek, Juho Kannala<br />CVPR 2020"
markdown: kramdown
