name: hscnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - imageio=2.5.0
  - matplotlib=3.0.2
  - numpy=1.15.4
  - opencv=3.4.2
  - pillow=5.4.1
  - pip=18.1
  - python=3.7.1
  - pytorch=1.0.1
  - scikit-image=0.14.1
  - scipy=1.1.0
  - shapely=1.6.4
  - six=1.12.0
  - torchvision=0.2.2
  - tqdm=4.28.1
  - pip:
    - cython==0.29.14
    - imgaug==0.2.6
